### Config
GET {{baseUrl}}/config/get-by-tenant/local
Authorization: Bearer {{token}}

###

GET {{baseUrl}}/auth

### Signup

POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "username": "sv_test2",
  "password": "asdfred"
}

### SignIn
POST {{baseUrl}}/auth/signin
Content-Type: application/json

{
  "username": "sv_test1",
  "password": "asdfred"
}

> {% client.global.set("token", response.body.token) %}

### Config